color             = "Always"
unstable_features = true
version           = "Two"

error_on_line_overflow = false
error_on_unformatted   = false

# stable features
chain_width                         = 60
edition                             = "2021"
fn_args_layout                      = "Vertical"
fn_call_width                       = 60
force_explicit_abi                  = true
hard_tabs                           = false
match_arm_leading_pipes             = "Preserve"
match_block_trailing_comma          = true
max_width                           = 120
merge_derives                       = true
newline_style                       = "Unix"
remove_nested_parens                = true
reorder_imports                     = true
reorder_modules                     = true
short_array_element_width_threshold = 10
struct_lit_width                    = 18
struct_variant_width                = 35
tab_spaces                          = 4

# unstable features
binop_separator               = "Front"
blank_lines_lower_bound       = 0
blank_lines_upper_bound       = 2
brace_style                   = "PreferSameLine"
combine_control_expr          = true
comment_width                 = 120
condense_wildcard_suffixes    = true
control_brace_style           = "AlwaysSameLine"
doc_comment_code_block_width  = 120
empty_item_single_line        = false
enum_discrim_align_threshold  = 20
fn_single_line                = true
force_multiline_blocks        = false
format_code_in_doc_comments   = true
format_generated_files        = true
format_macro_bodies           = true
format_macro_matchers         = true
format_strings                = true
group_imports                 = "StdExternalCrate"
hex_literal_case              = "Upper"
hide_parse_errors             = false
imports_granularity           = "Crate"
imports_indent                = "Block"
imports_layout                = "Vertical"
indent_style                  = "Block"
inline_attribute_width        = 0
match_arm_blocks              = false
normalize_comments            = true
normalize_doc_attributes      = false
overflow_delimited_expr       = false
reorder_impl_items            = true
single_line_if_else_max_width = 50
skip_children                 = false
space_after_colon             = true
space_before_colon            = false
spaces_around_ranges          = false
struct_field_align_threshold  = 20
struct_lit_single_line        = true
trailing_comma                = "Vertical"
trailing_semicolon            = true
type_punctuation_density      = "Compressed"
use_field_init_shorthand      = true
use_try_shorthand             = true
where_single_line             = true
wrap_comments                 = true

use_small_heuristics = "Off"

ignore = []
