name: Main

on:
  push:
    branches:
      - main
    paths:
      - '**/*.rs'
      - Cargo.toml
      - .cargo/config.toml
  workflow_dispatch:
  release:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os:
          - windows-latest
        target:
          - x86_64-pc-windows-msvc
          - x86_64-pc-windows-gnu

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Install nightly toolchain
        id: install-toolchain
        uses: ructions/toolchain@v2.0.0
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          profile: minimal
          default: true
          override: true

      - name: Cargo Check
        id: cargo-check
        run: cargo check

      - name: Build Release
        id: build-rel
        run: cargo build --release -Z=unstable-options --out-dir .
