name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install musl
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: cargo build --verbose
